version: '3.8'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
