# Generated by Django 4.2.3 on 2023-07-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='realtor',
            table='realtor',
        ),
    ]
